import { createFileRoute } from "@tanstack/react-router";
import { Action, ListeningPreview, Marketing, Meta, NextSteps, RequestSection, pageHead } from "@/components/Marketing";

export const Route = createFileRoute("/")({ staticData: { sitemap: true }, head: () => pageHead("Callwoven | AI reception for UK dental practices", "Callwoven provides reception overflow and out-of-hours call handling for UK dental practices, capturing routine enquiries and appointment requests for staff to follow up."), component: Home });

function Home() {
  return <Marketing>
    <section className="callwoven-hero"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-12 sm:px-8 sm:py-16 lg:min-h-[590px] lg:grid-cols-[1.08fr_0.92fr] lg:gap-14"><div><p className="inline-flex rounded-full bg-background/75 px-5 py-2 text-sm font-medium shadow-sm">AI reception for busy practices</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[0.95] sm:text-7xl lg:text-[84px]">Every call deserves<br className="hidden sm:block"/> a warm welcome.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted-foreground sm:text-xl">Answer enquiries, capture patient details and help your team follow up — even when reception is busy.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Action to="/demo">Hear Callwoven</Action><Action to="/" hash="pilot" secondary>Start a 7-day pilot</Action></div><p className="mt-6 text-sm text-muted-foreground">Built for dental practices. Ready for local businesses.</p></div><ListeningPreview/></div></section>
    <NextSteps/>
    <section className="mx-auto max-w-7xl px-5 py-18 sm:px-8 sm:py-24"><Meta eyebrow="Choose your Callwoven" title="Purpose-built call handling, shaped around your business.">Start with the calls your team already handles every day.</Meta><div className="mt-10 grid gap-5 lg:grid-cols-[1.15fr_1fr]"><article className="flex flex-col justify-between rounded-2xl border-2 border-primary bg-card p-7 sm:p-9"><div><p className="text-xs font-bold tracking-[0.14em] text-brand">CALLWOVEN DENTAL</p><h3 className="mt-7 text-3xl font-semibold sm:text-4xl">Patient calls handled when reception can't answer.</h3><p className="mt-4 leading-relaxed text-muted-foreground">New-patient enquiries · Appointment requests · Routine questions · Out-of-hours calls. Administrative support only — no clinical advice.</p></div><div className="mt-9"><Action to="/dental">Explore Callwoven Dental</Action></div></article><article className="flex flex-col justify-between rounded-2xl border border-border bg-card p-7 sm:p-9"><div><p className="text-xs font-bold tracking-[0.14em] text-brand">CALLWOVEN TRADES</p><h3 className="mt-7 text-3xl font-semibold">Customers answered while you're on the job.</h3><p className="mt-4 leading-relaxed text-muted-foreground">Lead details · Job requests · Priority flags · Out-of-hours calls.</p></div><div className="mt-9"><Action to="/trades" secondary>Explore Trades</Action></div></article></div></section>
    <section className="bg-brand-ink text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 md:grid-cols-2 md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.14em] opacity-75">Safe and in your control</p><h2 className="mt-4 text-4xl font-semibold sm:text-5xl">Callwoven follows your rules — not its own.</h2></div><ul className="space-y-3 text-sm leading-relaxed opacity-90">{["Uses only the information you approve.", "Escalation rules are set by your team.", "Anything uncertain or sensitive goes back to a person.", "Captures requests — it doesn't confirm bookings or give clinical advice."].map(x => <li key={x} className="border-b border-primary-foreground/15 pb-3">{x}</li>)}</ul></div></section>
    <div id="pilot"><RequestSection source="home" title="A warmer welcome, shaped around your business." buttonText="Start a 7-day pilot" /></div>
  </Marketing>;
}