import { Link } from "@tanstack/react-router";
import { useState, type ReactNode } from "react";
import { ArrowUpRight, ClipboardList, Menu, Phone, UserRound, UsersRound, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PilotForm as PilotFormBridge } from "@/components/PilotForm";
import { DEMO_NUMBERS } from "@/lib/demo-config";

export function Mark({ descriptor }: { descriptor?: string | undefined }) {
  return <span className="inline-flex min-w-0 items-center gap-2.5"><svg viewBox="0 0 44 44" className="h-9 w-9 shrink-0" role="img" aria-label="Callwoven woven mark"><path d="M12 8c-5 0-8 3-8 8 0 3 2 5 5 8l13 12c3 3 8 2 10-1 2-3 1-7-2-10L17 12c-2-2-3-4-5-4Z" fill="none" className="stroke-blush" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><path d="M32 8c5 0 8 3 8 8 0 3-2 5-5 8L22 36c-3 3-8 2-10-1-2-3-1-7 2-10l13-13c2-2 3-4 5-4Z" fill="none" className="stroke-powder" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/></svg><span className="flex min-w-0 flex-col leading-none"><strong className="font-display text-[28px] font-semibold leading-none">callwoven</strong>{descriptor && <span className="mt-1 text-[9px] font-bold uppercase tracking-[0.14em] text-muted-foreground">{descriptor}</span>}</span></span>;
}

const nav = [{ label: "Dental", to: "/dental" }, { label: "Trades", to: "/trades" }, { label: "How it works", to: "/how-it-works" }, { label: "Pricing", to: "/pricing" }] as const;

export function Marketing({ children, descriptor }: { children: ReactNode; descriptor?: string | undefined }) {
  const [open, setOpen] = useState(false);
  return <div className="min-h-screen overflow-x-hidden bg-background text-foreground"><a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[70] focus:rounded-md focus:bg-background focus:px-4 focus:py-3">Skip to content</a><header className="sticky top-0 z-50 border-b border-border/70 bg-background/95 backdrop-blur"><div className="mx-auto grid h-[74px] max-w-7xl grid-cols-[minmax(0,1fr)_auto] items-center gap-4 px-5 sm:px-8 lg:grid-cols-[1fr_auto_1fr]"><Link to="/" aria-label="Callwoven home" onClick={() => setOpen(false)} className="min-w-0 justify-self-start"><Mark descriptor={descriptor}/></Link><nav aria-label="Main" className="hidden items-center gap-9 text-sm font-medium lg:flex">{nav.map(n => <Link key={n.to} to={n.to} activeProps={{ className: "text-brand" }} className="transition-colors hover:text-brand">{n.label}</Link>)}</nav><div className="hidden justify-self-end lg:flex"><Button asChild size="lg" className="h-12 rounded-full px-7"><Link to="/demo">Hear Callwoven <ArrowUpRight /></Link></Button></div><Button variant="ghost" size="icon" aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open} aria-controls="mobile-nav" className="shrink-0 lg:hidden" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</Button></div>{open && <nav id="mobile-nav" aria-label="Mobile" className="border-t border-border bg-background px-5 py-4 lg:hidden">{nav.map(n => <Link key={n.to} to={n.to} onClick={() => setOpen(false)} className="block border-b border-border py-3.5 text-sm font-semibold">{n.label}</Link>)}<Button asChild className="mt-4 h-12 w-full rounded-full"><Link to="/demo" onClick={() => setOpen(false)}>Hear Callwoven <ArrowUpRight /></Link></Button></nav>}</header><main id="main">{children}</main><footer className="border-t border-border bg-warm"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-12 sm:flex-row sm:items-end sm:justify-between sm:px-8"><div><Link to="/" aria-label="Callwoven home"><Mark /></Link><p className="mt-4 max-w-sm text-sm text-muted-foreground">AI call handling for UK dental practices and trades businesses.</p></div><nav aria-label="Footer" className="flex flex-wrap gap-x-5 gap-y-3 text-sm font-medium">{nav.map(n => <Link key={n.to} to={n.to} className="hover:text-brand">{n.label}</Link>)}<Link to="/demo" className="hover:text-brand">Demo</Link><Link to="/privacy" className="hover:text-brand">Privacy</Link></nav></div><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-2 border-t border-border px-5 py-5 text-xs text-muted-foreground sm:px-8"><span>© {new Date().getFullYear()} Callwoven. A trading name of T Satya Narayana Reddy, sole proprietor based in India.</span><Link to="/login" className="hover:text-foreground">Owner login</Link></div></footer></div>;
}

export function Meta({ eyebrow, title, children, as = "h2" }: { eyebrow: string; title: string; children?: ReactNode; as?: "h1" | "h2" }) { const H = as; return <div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand">{eyebrow}</p><H className="mt-4 text-4xl font-semibold leading-[1.05] sm:text-5xl">{title}</H>{children && <p className="mt-5 text-base leading-relaxed text-muted-foreground sm:text-lg">{children}</p>}</div>; }
type To = "/" | "/demo" | "/how-it-works" | "/pricing" | "/dental" | "/trades" | "/privacy";
export function Action({ to, children, secondary = false, hash }: { to: To; children: ReactNode; secondary?: boolean; hash?: string }) { return <Button asChild variant={secondary ? "outline" : "default"} size="lg" className="h-14 w-full rounded-full px-7 sm:w-auto"><Link to={to} {...(hash ? { hash } : {})}>{children}<ArrowUpRight /></Link></Button>; }

export function ListeningPreview() {
  const bars = [14, 25, 18, 34, 22, 43, 29, 18, 32, 47, 30, 20, 37, 26, 17, 32, 22, 14];
  return <div className="relative mx-auto w-full max-w-[510px] pb-16 pt-10 sm:pb-20"><p className="absolute right-2 top-0 -rotate-3 text-xs italic text-muted-foreground">↙ &nbsp; Illustrative demo</p><div className="relative ml-auto w-[88%] rotate-[3deg] rounded-[22px] border border-background/80 bg-card/95 px-6 py-8 text-center shadow-[0_24px_60px_-28px_color-mix(in_oklab,var(--brand-ink)_28%,transparent)] sm:px-10 sm:py-10"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-blush/75"><Phone className="h-7 w-7" aria-hidden="true"/></div><div className="mx-auto mt-7 flex h-14 items-center justify-center gap-1" aria-hidden="true">{bars.map((height, i) => <span key={`${height}-${i}`} className="w-1 rounded-full bg-foreground" style={{ height }}/>)}</div><p className="mt-6 text-lg font-bold">Callwoven is listening</p><p className="mt-1 text-sm text-muted-foreground">New patient enquiry</p></div><div className="absolute bottom-0 right-0 w-[78%] rounded-2xl border border-border bg-card p-5 shadow-[0_18px_50px_-25px_color-mix(in_oklab,var(--brand-ink)_25%,transparent)] sm:w-[70%]"><div className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-4 gap-y-3"><div className="row-span-3 grid h-11 w-11 place-items-center rounded-full bg-powder"><ClipboardList className="h-5 w-5" aria-hidden="true"/></div><p className="font-bold">Call summary</p><p className="flex min-w-0 items-center gap-2 text-xs text-muted-foreground"><UserRound className="h-4 w-4 shrink-0"/>New patient · Check-up enquiry</p><p className="flex items-center gap-2 text-xs text-muted-foreground"><Phone className="h-4 w-4 shrink-0"/>Callback requested</p></div></div></div>;
}

export function NextSteps() { const cards = [{ icon: Phone, tone: "bg-blush/70", title: "Answer the call", text: "Callwoven responds using the information your business has approved." }, { icon: ClipboardList, tone: "bg-powder", title: "Capture the details", text: "Key information is gathered and organised for your team to review." }, { icon: UsersRound, tone: "bg-blush/70", title: "Keep your team informed", text: "A structured summary gives your team a clear next step for follow-up." }]; return <section className="bg-warm py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><h2 className="text-center text-4xl font-semibold leading-tight sm:text-5xl">A calmer front desk. A clearer next step.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{cards.map(({icon: Icon, tone, title, text}) => <article key={title} className="grid grid-cols-[auto_minmax(0,1fr)] gap-5 rounded-xl border border-border bg-background/50 p-6 sm:p-7"><div className={`grid h-14 w-14 shrink-0 place-items-center rounded-full ${tone}`}><Icon className="h-6 w-6" aria-hidden="true"/></div><div className="min-w-0"><h3 className="font-sans text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div></article>)}</div></div></section>; }

export function LeadPreview() { return <div className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-lg"><div className="flex items-center justify-between border-b border-border pb-4"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-brand">Illustrative lead</p><p className="mt-1 font-sans font-bold">New enquiry captured</p></div><span className="rounded-full bg-destructive/10 px-2.5 py-1 text-xs font-bold text-destructive">URGENT</span></div><dl className="mt-5 space-y-4 text-sm">{[["Caller", "Mrs D. Whitfield"], ["Phone", "07••• ••• 214"], ["Postcode", "LS15 8••"], ["Issue", "Boiler leaking; no hot water"], ["Next step", "Priority callback requested"]].map(([k,v]) => <div key={k} className="grid grid-cols-[90px_minmax(0,1fr)] gap-3"><dt className="text-muted-foreground">{k}</dt><dd className="font-semibold">{v}</dd></div>)}</dl><p className="mt-6 border-t border-border pt-4 text-xs text-muted-foreground">Fictional example — not a real customer record.</p></div>; }

export function DemoPanel({ vertical, prompts, note, primary = false }: { vertical: "dental" | "trades"; prompts: string[]; note?: ReactNode; primary?: boolean }) { const label = vertical === "dental" ? "Dental" : "Trades"; const number = DEMO_NUMBERS[vertical]?.trim() || null; return <article className={`flex flex-col rounded-2xl bg-card p-7 sm:p-9 ${primary ? "border-2 border-primary" : "border border-border"}`}><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-bold tracking-[0.14em] text-brand">CALLWOVEN {label.toUpperCase()} DEMO</p><span className="rounded-full bg-brand-soft px-3 py-1 text-xs font-bold text-foreground">{number ? "Call the demo" : "Demo by request"}</span></div><h3 className="mt-5 text-3xl font-semibold">Try asking:</h3><ul className="mt-5 flex-1 space-y-3">{prompts.map(p => <li key={p} className="rounded-lg border-l-2 border-brand bg-muted/60 px-4 py-3 text-sm font-semibold">“{p}”</li>)}</ul>{note && <p className="mt-4 text-sm leading-relaxed text-muted-foreground">{note}</p>}<div className="mt-7">{number ? <Button asChild size="lg" className="h-14 w-full rounded-full sm:w-auto"><a href={`tel:${number.replace(/\s/g, "")}`}><Phone /> Call Callwoven {label} — {number}</a></Button> : <Action to="/demo" hash="request-demo">Request a demo</Action>}</div></article>; }
export const DENTAL_PROMPTS = ["Are you accepting new patients?", "I'd like a cosmetic consultation.", "Can I request an appointment next Tuesday afternoon?", "What time do you close?", "I have a clinical question."];
export const DENTAL_PROMPT_NOTE = <>For clinical questions, Callwoven defers to people: it takes a callback request for the practice team rather than giving an answer.</>;
export const TRADES_PROMPTS = ["There's water leaking under my boiler.", "Can I get a quote for a new radiator?", "Could someone call me back this afternoon?", "Do you cover my area?"];
export function RequestSection({ title, source, kind = "pilot", buttonText, intro }: { title: string; source: "home" | "dental" | "trades" | "demo"; kind?: "pilot" | "demo"; buttonText?: string; intro?: string }) { return <section className="border-t border-border bg-powder/25 py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand">{kind === "demo" ? "Arrange a demo" : "7-day pilot"}</p><h2 className="mt-4 max-w-lg text-4xl font-semibold leading-[1.05] sm:text-5xl">{title}</h2><p className="mt-5 max-w-md leading-relaxed text-muted-foreground">{intro ?? (kind === "demo" ? "Tell us about your business and we'll contact you to arrange a tailored demo." : "Tell us about your business to discuss a free 7-day pilot tailored to your calls. We'll agree the setup, safeguards, pricing and service terms before any calls are connected.")}</p></div><div className="min-w-0 max-w-2xl"><PilotFormBridge source={source} kind={kind} buttonText={buttonText}/></div></div></section>; }
export function pageHead(title: string, description: string) { return { meta: [{ title }, { name: "description", content: description }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }; }